export const FETCH_SCORE_DATA = "FETCH_SCORE_DATA";
export const CREATE_SCORE_DATA = "CREATE_SCORE_DATA";
export const UPDATE_SCORE_DATA = "UPDATE_SCORE_DATA";
export const DELETE_SCORE_DATA = "DELETE_SCORE_DATA";
